### ISSUE TITLE
can you upload the CAD files please? 

### ISSUE THREAD

**Issue by mathewlippincott** [OpenLabTools/Microscope#4]
Could you please upload 2D or 3D CAD files from the design software you used? 
The STL files uploaded are great for replication, but mesh files aren't very useful for modifying parts.

**Comment by Somahtr** [comment]
Hi @mathewlippincott. I've managed to track down the original CAD files in SolidWorks format, see 62e07dc827f882cb995bdb6c302bdf92099a08ff. I hope that they are useful!

**Comment by mathewlippincott** [comment]
awesome! thank you.
